# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rename Me
email: re@name.me
description: > # this means to ignore newlines until "baseurl:"
  Add a description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://*.rename.me" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
source: src
destination: _site
keep_files: ["fonts","css", "images", "javascripts"]
encoding: utf-8

gems:
  - jekyll-sitemap