# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rename Me
email: re@name.me
description: > # this means to ignore newlines until "baseurl:"
  Springbox is a digital agency with offices in Austin and Los Angeles. We help our partners reach their goals with expert research, strategy and execution.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://*.springbox.com" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
source: src
destination: _site
keep_files: ["fonts","css", "images", "javascripts"]
encoding: utf-8
